#!/bin/bash
#Filename: time_take.sh
start=$(date +%s)
echo Command1
echo Command2
echo And another command...
echo ...and another.
echo And another command...
echo ...and another.
echo And another command...
echo ...and another.
echo And another command...
echo ...and another.
echo And another command...
echo ...and another.
echo And another command...
echo ...and another.
echo And another command...
echo ...and another.
echo And another command...
echo ...and another.
echo And another command...
echo ...and another.
echo And another command...
echo ...and another.
echo And another command...
echo ...and another.
echo And another command...
echo ...and another.
echo And another command...
echo ...and another.
echo And another command...
echo ...and another.
echo "4000000000 * 0.55555555555555" | bc
echo And that should do it.
end=$(date +%s)
difference=$(( end - start))
echo Time taken to execute commands is $difference seconds.
